
namespace Enchanter_Fashion.inventory
{
    partial class form_dashboard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(form_dashboard));
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.panelControls = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnexit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnuser = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btninv = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnorder = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnsup = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnitem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btncat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnhome = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // panelControls
            // 
            this.panelControls.BackgroundColor = System.Drawing.Color.White;
            resources.ApplyResources(this.panelControls, "panelControls");
            this.panelControls.BorderColor = System.Drawing.Color.Transparent;
            this.panelControls.BorderRadius = 10;
            this.panelControls.BorderThickness = 1;
            this.panelControls.Name = "panelControls";
            this.panelControls.ShowBorders = true;
            this.panelControls.Click += new System.EventHandler(this.panelControls_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            resources.ApplyResources(this.bunifuPanel1, "bunifuPanel1");
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btnexit);
            this.bunifuPanel1.Controls.Add(this.btnuser);
            this.bunifuPanel1.Controls.Add(this.btninv);
            this.bunifuPanel1.Controls.Add(this.btnorder);
            this.bunifuPanel1.Controls.Add(this.btnsup);
            this.bunifuPanel1.Controls.Add(this.btnitem);
            this.bunifuPanel1.Controls.Add(this.btncat);
            this.bunifuPanel1.Controls.Add(this.btnhome);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            // 
            // btnexit
            // 
            this.btnexit.AllowAnimations = true;
            this.btnexit.AllowMouseEffects = true;
            this.btnexit.AllowToggling = false;
            this.btnexit.AnimationSpeed = 200;
            this.btnexit.AutoGenerateColors = true;
            this.btnexit.AutoRoundBorders = true;
            this.btnexit.AutoSizeLeftIcon = true;
            this.btnexit.AutoSizeRightIcon = true;
            this.btnexit.BackColor = System.Drawing.Color.Transparent;
            this.btnexit.BackColor1 = System.Drawing.Color.Silver;
            resources.ApplyResources(this.btnexit, "btnexit");
            this.btnexit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnexit.ButtonText = "Exit";
            this.btnexit.ButtonTextMarginLeft = 0;
            this.btnexit.ColorContrastOnClick = 45;
            this.btnexit.ColorContrastOnHover = 45;
            this.btnexit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnexit.CustomizableEdges = borderEdges1;
            this.btnexit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnexit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnexit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnexit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnexit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnexit.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btnexit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnexit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnexit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 5, 3);
            this.btnexit.IconMarginLeft = 11;
            this.btnexit.IconPadding = 10;
            this.btnexit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnexit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnexit.IconRightPadding = new System.Windows.Forms.Padding(3);
            this.btnexit.IconSize = 25;
            this.btnexit.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btnexit.IdleBorderRadius = 38;
            this.btnexit.IdleBorderThickness = 1;
            this.btnexit.IdleFillColor = System.Drawing.Color.Silver;
            this.btnexit.IdleIconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btnexit.IdleIconRightImage = null;
            this.btnexit.IndicateFocus = true;
            this.btnexit.Name = "btnexit";
            this.btnexit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnexit.OnDisabledState.BorderRadius = 45;
            this.btnexit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnexit.OnDisabledState.BorderThickness = 1;
            this.btnexit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnexit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnexit.OnDisabledState.IconLeftImage = null;
            this.btnexit.OnDisabledState.IconRightImage = null;
            this.btnexit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            this.btnexit.onHoverState.BorderRadius = 45;
            this.btnexit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnexit.onHoverState.BorderThickness = 1;
            this.btnexit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(220)))));
            this.btnexit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnexit.onHoverState.IconLeftImage = null;
            this.btnexit.onHoverState.IconRightImage = null;
            this.btnexit.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnexit.OnIdleState.BorderRadius = 45;
            this.btnexit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnexit.OnIdleState.BorderThickness = 1;
            this.btnexit.OnIdleState.FillColor = System.Drawing.Color.Silver;
            this.btnexit.OnIdleState.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btnexit.OnIdleState.IconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btnexit.OnIdleState.IconRightImage = null;
            this.btnexit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(132)))), ((int)(((byte)(132)))), ((int)(((byte)(132)))));
            this.btnexit.OnPressedState.BorderRadius = 45;
            this.btnexit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnexit.OnPressedState.BorderThickness = 1;
            this.btnexit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.btnexit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnexit.OnPressedState.IconLeftImage = null;
            this.btnexit.OnPressedState.IconRightImage = null;
            this.btnexit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnexit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnexit.TextMarginLeft = 0;
            this.btnexit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnexit.UseDefaultRadiusAndThickness = true;
            this.btnexit.Click += new System.EventHandler(this.btnexit_Click);
            // 
            // btnuser
            // 
            this.btnuser.AllowAnimations = true;
            this.btnuser.AllowMouseEffects = true;
            this.btnuser.AllowToggling = false;
            this.btnuser.AnimationSpeed = 200;
            this.btnuser.AutoGenerateColors = true;
            this.btnuser.AutoRoundBorders = true;
            this.btnuser.AutoSizeLeftIcon = true;
            this.btnuser.AutoSizeRightIcon = true;
            this.btnuser.BackColor = System.Drawing.Color.Transparent;
            this.btnuser.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(188)))), ((int)(((byte)(188)))));
            resources.ApplyResources(this.btnuser, "btnuser");
            this.btnuser.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnuser.ButtonText = "Users";
            this.btnuser.ButtonTextMarginLeft = 0;
            this.btnuser.ColorContrastOnClick = 45;
            this.btnuser.ColorContrastOnHover = 45;
            this.btnuser.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnuser.CustomizableEdges = borderEdges2;
            this.btnuser.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnuser.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnuser.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnuser.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnuser.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnuser.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(240)))), ((int)(((byte)(245)))));
            this.btnuser.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnuser.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnuser.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 5, 3);
            this.btnuser.IconMarginLeft = 11;
            this.btnuser.IconPadding = 10;
            this.btnuser.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnuser.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnuser.IconRightPadding = new System.Windows.Forms.Padding(3);
            this.btnuser.IconSize = 25;
            this.btnuser.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.btnuser.IdleBorderRadius = 38;
            this.btnuser.IdleBorderThickness = 1;
            this.btnuser.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(188)))), ((int)(((byte)(188)))));
            this.btnuser.IdleIconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btnuser.IdleIconRightImage = null;
            this.btnuser.IndicateFocus = true;
            this.btnuser.Name = "btnuser";
            this.btnuser.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnuser.OnDisabledState.BorderRadius = 45;
            this.btnuser.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnuser.OnDisabledState.BorderThickness = 1;
            this.btnuser.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnuser.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnuser.OnDisabledState.IconLeftImage = null;
            this.btnuser.OnDisabledState.IconRightImage = null;
            this.btnuser.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            this.btnuser.onHoverState.BorderRadius = 45;
            this.btnuser.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnuser.onHoverState.BorderThickness = 1;
            this.btnuser.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(218)))), ((int)(((byte)(218)))), ((int)(((byte)(218)))));
            this.btnuser.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnuser.onHoverState.IconLeftImage = null;
            this.btnuser.onHoverState.IconRightImage = null;
            this.btnuser.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.btnuser.OnIdleState.BorderRadius = 45;
            this.btnuser.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnuser.OnIdleState.BorderThickness = 1;
            this.btnuser.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(188)))), ((int)(((byte)(188)))), ((int)(((byte)(188)))));
            this.btnuser.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(240)))), ((int)(((byte)(245)))));
            this.btnuser.OnIdleState.IconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btnuser.OnIdleState.IconRightImage = null;
            this.btnuser.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(132)))), ((int)(((byte)(132)))), ((int)(((byte)(132)))));
            this.btnuser.OnPressedState.BorderRadius = 45;
            this.btnuser.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnuser.OnPressedState.BorderThickness = 1;
            this.btnuser.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(103)))), ((int)(((byte)(103)))), ((int)(((byte)(103)))));
            this.btnuser.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnuser.OnPressedState.IconLeftImage = null;
            this.btnuser.OnPressedState.IconRightImage = null;
            this.btnuser.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnuser.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnuser.TextMarginLeft = 0;
            this.btnuser.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnuser.UseDefaultRadiusAndThickness = true;
            this.btnuser.Click += new System.EventHandler(this.btnuser_Click);
            // 
            // btninv
            // 
            this.btninv.AllowAnimations = true;
            this.btninv.AllowMouseEffects = true;
            this.btninv.AllowToggling = false;
            this.btninv.AnimationSpeed = 200;
            this.btninv.AutoGenerateColors = true;
            this.btninv.AutoRoundBorders = true;
            this.btninv.AutoSizeLeftIcon = true;
            this.btninv.AutoSizeRightIcon = true;
            this.btninv.BackColor = System.Drawing.Color.Transparent;
            this.btninv.BackColor1 = System.Drawing.Color.Silver;
            resources.ApplyResources(this.btninv, "btninv");
            this.btninv.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btninv.ButtonText = "Invoices";
            this.btninv.ButtonTextMarginLeft = 0;
            this.btninv.ColorContrastOnClick = 45;
            this.btninv.ColorContrastOnHover = 45;
            this.btninv.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btninv.CustomizableEdges = borderEdges3;
            this.btninv.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btninv.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btninv.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btninv.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btninv.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btninv.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btninv.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btninv.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btninv.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 5, 3);
            this.btninv.IconMarginLeft = 11;
            this.btninv.IconPadding = 10;
            this.btninv.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btninv.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btninv.IconRightPadding = new System.Windows.Forms.Padding(3);
            this.btninv.IconSize = 25;
            this.btninv.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btninv.IdleBorderRadius = 38;
            this.btninv.IdleBorderThickness = 1;
            this.btninv.IdleFillColor = System.Drawing.Color.Silver;
            this.btninv.IdleIconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btninv.IdleIconRightImage = null;
            this.btninv.IndicateFocus = true;
            this.btninv.Name = "btninv";
            this.btninv.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btninv.OnDisabledState.BorderRadius = 45;
            this.btninv.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btninv.OnDisabledState.BorderThickness = 1;
            this.btninv.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btninv.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btninv.OnDisabledState.IconLeftImage = null;
            this.btninv.OnDisabledState.IconRightImage = null;
            this.btninv.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            this.btninv.onHoverState.BorderRadius = 45;
            this.btninv.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btninv.onHoverState.BorderThickness = 1;
            this.btninv.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(220)))));
            this.btninv.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btninv.onHoverState.IconLeftImage = null;
            this.btninv.onHoverState.IconRightImage = null;
            this.btninv.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btninv.OnIdleState.BorderRadius = 45;
            this.btninv.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btninv.OnIdleState.BorderThickness = 1;
            this.btninv.OnIdleState.FillColor = System.Drawing.Color.Silver;
            this.btninv.OnIdleState.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btninv.OnIdleState.IconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btninv.OnIdleState.IconRightImage = null;
            this.btninv.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(132)))), ((int)(((byte)(132)))), ((int)(((byte)(132)))));
            this.btninv.OnPressedState.BorderRadius = 45;
            this.btninv.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btninv.OnPressedState.BorderThickness = 1;
            this.btninv.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.btninv.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btninv.OnPressedState.IconLeftImage = null;
            this.btninv.OnPressedState.IconRightImage = null;
            this.btninv.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btninv.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btninv.TextMarginLeft = 0;
            this.btninv.TextPadding = new System.Windows.Forms.Padding(0);
            this.btninv.UseDefaultRadiusAndThickness = true;
            this.btninv.Click += new System.EventHandler(this.btninv_Click);
            // 
            // btnorder
            // 
            this.btnorder.AllowAnimations = true;
            this.btnorder.AllowMouseEffects = true;
            this.btnorder.AllowToggling = false;
            this.btnorder.AnimationSpeed = 200;
            this.btnorder.AutoGenerateColors = true;
            this.btnorder.AutoRoundBorders = true;
            this.btnorder.AutoSizeLeftIcon = true;
            this.btnorder.AutoSizeRightIcon = true;
            this.btnorder.BackColor = System.Drawing.Color.Transparent;
            this.btnorder.BackColor1 = System.Drawing.Color.Silver;
            resources.ApplyResources(this.btnorder, "btnorder");
            this.btnorder.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnorder.ButtonText = "Orders";
            this.btnorder.ButtonTextMarginLeft = 0;
            this.btnorder.ColorContrastOnClick = 45;
            this.btnorder.ColorContrastOnHover = 45;
            this.btnorder.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnorder.CustomizableEdges = borderEdges4;
            this.btnorder.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnorder.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnorder.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnorder.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnorder.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnorder.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btnorder.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnorder.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnorder.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 5, 3);
            this.btnorder.IconMarginLeft = 11;
            this.btnorder.IconPadding = 10;
            this.btnorder.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnorder.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnorder.IconRightPadding = new System.Windows.Forms.Padding(3);
            this.btnorder.IconSize = 25;
            this.btnorder.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btnorder.IdleBorderRadius = 38;
            this.btnorder.IdleBorderThickness = 1;
            this.btnorder.IdleFillColor = System.Drawing.Color.Silver;
            this.btnorder.IdleIconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btnorder.IdleIconRightImage = null;
            this.btnorder.IndicateFocus = true;
            this.btnorder.Name = "btnorder";
            this.btnorder.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnorder.OnDisabledState.BorderRadius = 45;
            this.btnorder.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnorder.OnDisabledState.BorderThickness = 1;
            this.btnorder.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnorder.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnorder.OnDisabledState.IconLeftImage = null;
            this.btnorder.OnDisabledState.IconRightImage = null;
            this.btnorder.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            this.btnorder.onHoverState.BorderRadius = 45;
            this.btnorder.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnorder.onHoverState.BorderThickness = 1;
            this.btnorder.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(220)))));
            this.btnorder.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnorder.onHoverState.IconLeftImage = null;
            this.btnorder.onHoverState.IconRightImage = null;
            this.btnorder.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnorder.OnIdleState.BorderRadius = 45;
            this.btnorder.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnorder.OnIdleState.BorderThickness = 1;
            this.btnorder.OnIdleState.FillColor = System.Drawing.Color.Silver;
            this.btnorder.OnIdleState.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btnorder.OnIdleState.IconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btnorder.OnIdleState.IconRightImage = null;
            this.btnorder.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(132)))), ((int)(((byte)(132)))), ((int)(((byte)(132)))));
            this.btnorder.OnPressedState.BorderRadius = 45;
            this.btnorder.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnorder.OnPressedState.BorderThickness = 1;
            this.btnorder.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.btnorder.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnorder.OnPressedState.IconLeftImage = null;
            this.btnorder.OnPressedState.IconRightImage = null;
            this.btnorder.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnorder.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnorder.TextMarginLeft = 0;
            this.btnorder.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnorder.UseDefaultRadiusAndThickness = true;
            this.btnorder.Click += new System.EventHandler(this.btnorder_Click);
            // 
            // btnsup
            // 
            this.btnsup.AllowAnimations = true;
            this.btnsup.AllowMouseEffects = true;
            this.btnsup.AllowToggling = false;
            this.btnsup.AnimationSpeed = 200;
            this.btnsup.AutoGenerateColors = true;
            this.btnsup.AutoRoundBorders = true;
            this.btnsup.AutoSizeLeftIcon = true;
            this.btnsup.AutoSizeRightIcon = true;
            this.btnsup.BackColor = System.Drawing.Color.Transparent;
            this.btnsup.BackColor1 = System.Drawing.Color.Silver;
            resources.ApplyResources(this.btnsup, "btnsup");
            this.btnsup.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsup.ButtonText = "Suppliers";
            this.btnsup.ButtonTextMarginLeft = 0;
            this.btnsup.ColorContrastOnClick = 45;
            this.btnsup.ColorContrastOnHover = 45;
            this.btnsup.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnsup.CustomizableEdges = borderEdges5;
            this.btnsup.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnsup.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsup.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsup.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsup.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnsup.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btnsup.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnsup.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnsup.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 5, 3);
            this.btnsup.IconMarginLeft = 11;
            this.btnsup.IconPadding = 10;
            this.btnsup.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnsup.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnsup.IconRightPadding = new System.Windows.Forms.Padding(3);
            this.btnsup.IconSize = 25;
            this.btnsup.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btnsup.IdleBorderRadius = 38;
            this.btnsup.IdleBorderThickness = 1;
            this.btnsup.IdleFillColor = System.Drawing.Color.Silver;
            this.btnsup.IdleIconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btnsup.IdleIconRightImage = null;
            this.btnsup.IndicateFocus = true;
            this.btnsup.Name = "btnsup";
            this.btnsup.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsup.OnDisabledState.BorderRadius = 45;
            this.btnsup.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsup.OnDisabledState.BorderThickness = 1;
            this.btnsup.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsup.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsup.OnDisabledState.IconLeftImage = null;
            this.btnsup.OnDisabledState.IconRightImage = null;
            this.btnsup.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            this.btnsup.onHoverState.BorderRadius = 45;
            this.btnsup.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsup.onHoverState.BorderThickness = 1;
            this.btnsup.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(220)))));
            this.btnsup.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnsup.onHoverState.IconLeftImage = null;
            this.btnsup.onHoverState.IconRightImage = null;
            this.btnsup.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnsup.OnIdleState.BorderRadius = 45;
            this.btnsup.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsup.OnIdleState.BorderThickness = 1;
            this.btnsup.OnIdleState.FillColor = System.Drawing.Color.Silver;
            this.btnsup.OnIdleState.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btnsup.OnIdleState.IconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btnsup.OnIdleState.IconRightImage = null;
            this.btnsup.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(132)))), ((int)(((byte)(132)))), ((int)(((byte)(132)))));
            this.btnsup.OnPressedState.BorderRadius = 45;
            this.btnsup.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsup.OnPressedState.BorderThickness = 1;
            this.btnsup.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.btnsup.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnsup.OnPressedState.IconLeftImage = null;
            this.btnsup.OnPressedState.IconRightImage = null;
            this.btnsup.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnsup.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnsup.TextMarginLeft = 0;
            this.btnsup.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnsup.UseDefaultRadiusAndThickness = true;
            this.btnsup.Click += new System.EventHandler(this.btnsup_Click);
            // 
            // btnitem
            // 
            this.btnitem.AllowAnimations = true;
            this.btnitem.AllowMouseEffects = true;
            this.btnitem.AllowToggling = false;
            this.btnitem.AnimationSpeed = 200;
            this.btnitem.AutoGenerateColors = true;
            this.btnitem.AutoRoundBorders = true;
            this.btnitem.AutoSizeLeftIcon = true;
            this.btnitem.AutoSizeRightIcon = true;
            this.btnitem.BackColor = System.Drawing.Color.Transparent;
            this.btnitem.BackColor1 = System.Drawing.Color.Silver;
            resources.ApplyResources(this.btnitem, "btnitem");
            this.btnitem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnitem.ButtonText = "Items";
            this.btnitem.ButtonTextMarginLeft = 0;
            this.btnitem.ColorContrastOnClick = 45;
            this.btnitem.ColorContrastOnHover = 45;
            this.btnitem.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnitem.CustomizableEdges = borderEdges6;
            this.btnitem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnitem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnitem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnitem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnitem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnitem.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btnitem.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnitem.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnitem.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 5, 3);
            this.btnitem.IconMarginLeft = 11;
            this.btnitem.IconPadding = 10;
            this.btnitem.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnitem.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnitem.IconRightPadding = new System.Windows.Forms.Padding(3);
            this.btnitem.IconSize = 25;
            this.btnitem.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btnitem.IdleBorderRadius = 38;
            this.btnitem.IdleBorderThickness = 1;
            this.btnitem.IdleFillColor = System.Drawing.Color.Silver;
            this.btnitem.IdleIconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btnitem.IdleIconRightImage = null;
            this.btnitem.IndicateFocus = true;
            this.btnitem.Name = "btnitem";
            this.btnitem.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnitem.OnDisabledState.BorderRadius = 45;
            this.btnitem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnitem.OnDisabledState.BorderThickness = 1;
            this.btnitem.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnitem.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnitem.OnDisabledState.IconLeftImage = null;
            this.btnitem.OnDisabledState.IconRightImage = null;
            this.btnitem.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            this.btnitem.onHoverState.BorderRadius = 45;
            this.btnitem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnitem.onHoverState.BorderThickness = 1;
            this.btnitem.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(220)))));
            this.btnitem.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnitem.onHoverState.IconLeftImage = null;
            this.btnitem.onHoverState.IconRightImage = null;
            this.btnitem.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnitem.OnIdleState.BorderRadius = 45;
            this.btnitem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnitem.OnIdleState.BorderThickness = 1;
            this.btnitem.OnIdleState.FillColor = System.Drawing.Color.Silver;
            this.btnitem.OnIdleState.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btnitem.OnIdleState.IconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btnitem.OnIdleState.IconRightImage = null;
            this.btnitem.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(132)))), ((int)(((byte)(132)))), ((int)(((byte)(132)))));
            this.btnitem.OnPressedState.BorderRadius = 45;
            this.btnitem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnitem.OnPressedState.BorderThickness = 1;
            this.btnitem.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.btnitem.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnitem.OnPressedState.IconLeftImage = null;
            this.btnitem.OnPressedState.IconRightImage = null;
            this.btnitem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnitem.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnitem.TextMarginLeft = 0;
            this.btnitem.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnitem.UseDefaultRadiusAndThickness = true;
            this.btnitem.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // btncat
            // 
            this.btncat.AllowAnimations = true;
            this.btncat.AllowMouseEffects = true;
            this.btncat.AllowToggling = false;
            this.btncat.AnimationSpeed = 200;
            this.btncat.AutoGenerateColors = true;
            this.btncat.AutoRoundBorders = true;
            this.btncat.AutoSizeLeftIcon = true;
            this.btncat.AutoSizeRightIcon = true;
            this.btncat.BackColor = System.Drawing.Color.Transparent;
            this.btncat.BackColor1 = System.Drawing.Color.Silver;
            resources.ApplyResources(this.btncat, "btncat");
            this.btncat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btncat.ButtonText = "Categories";
            this.btncat.ButtonTextMarginLeft = 0;
            this.btncat.ColorContrastOnClick = 45;
            this.btncat.ColorContrastOnHover = 45;
            this.btncat.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btncat.CustomizableEdges = borderEdges7;
            this.btncat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btncat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btncat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btncat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btncat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btncat.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btncat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btncat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btncat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 5, 3);
            this.btncat.IconMarginLeft = 11;
            this.btncat.IconPadding = 10;
            this.btncat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btncat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btncat.IconRightPadding = new System.Windows.Forms.Padding(3);
            this.btncat.IconSize = 25;
            this.btncat.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btncat.IdleBorderRadius = 38;
            this.btncat.IdleBorderThickness = 1;
            this.btncat.IdleFillColor = System.Drawing.Color.Silver;
            this.btncat.IdleIconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btncat.IdleIconRightImage = null;
            this.btncat.IndicateFocus = true;
            this.btncat.Name = "btncat";
            this.btncat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btncat.OnDisabledState.BorderRadius = 45;
            this.btncat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btncat.OnDisabledState.BorderThickness = 1;
            this.btncat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btncat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btncat.OnDisabledState.IconLeftImage = null;
            this.btncat.OnDisabledState.IconRightImage = null;
            this.btncat.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            this.btncat.onHoverState.BorderRadius = 45;
            this.btncat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btncat.onHoverState.BorderThickness = 1;
            this.btncat.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(220)))));
            this.btncat.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btncat.onHoverState.IconLeftImage = null;
            this.btncat.onHoverState.IconRightImage = null;
            this.btncat.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btncat.OnIdleState.BorderRadius = 45;
            this.btncat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btncat.OnIdleState.BorderThickness = 1;
            this.btncat.OnIdleState.FillColor = System.Drawing.Color.Silver;
            this.btncat.OnIdleState.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btncat.OnIdleState.IconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btncat.OnIdleState.IconRightImage = null;
            this.btncat.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(132)))), ((int)(((byte)(132)))), ((int)(((byte)(132)))));
            this.btncat.OnPressedState.BorderRadius = 45;
            this.btncat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btncat.OnPressedState.BorderThickness = 1;
            this.btncat.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.btncat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btncat.OnPressedState.IconLeftImage = null;
            this.btncat.OnPressedState.IconRightImage = null;
            this.btncat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btncat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btncat.TextMarginLeft = 0;
            this.btncat.TextPadding = new System.Windows.Forms.Padding(0);
            this.btncat.UseDefaultRadiusAndThickness = true;
            this.btncat.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // btnhome
            // 
            this.btnhome.AllowAnimations = true;
            this.btnhome.AllowMouseEffects = true;
            this.btnhome.AllowToggling = false;
            this.btnhome.AnimationSpeed = 200;
            this.btnhome.AutoGenerateColors = true;
            this.btnhome.AutoRoundBorders = true;
            this.btnhome.AutoSizeLeftIcon = true;
            this.btnhome.AutoSizeRightIcon = true;
            this.btnhome.BackColor = System.Drawing.Color.Transparent;
            this.btnhome.BackColor1 = System.Drawing.Color.Silver;
            resources.ApplyResources(this.btnhome, "btnhome");
            this.btnhome.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnhome.ButtonText = "Home";
            this.btnhome.ButtonTextMarginLeft = 0;
            this.btnhome.ColorContrastOnClick = 45;
            this.btnhome.ColorContrastOnHover = 45;
            this.btnhome.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnhome.CustomizableEdges = borderEdges8;
            this.btnhome.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnhome.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnhome.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnhome.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnhome.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnhome.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btnhome.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnhome.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnhome.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 5, 3);
            this.btnhome.IconMarginLeft = 11;
            this.btnhome.IconPadding = 10;
            this.btnhome.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnhome.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnhome.IconRightPadding = new System.Windows.Forms.Padding(3);
            this.btnhome.IconSize = 25;
            this.btnhome.IdleBorderColor = System.Drawing.SystemColors.Control;
            this.btnhome.IdleBorderRadius = 38;
            this.btnhome.IdleBorderThickness = 1;
            this.btnhome.IdleFillColor = System.Drawing.Color.Silver;
            this.btnhome.IdleIconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btnhome.IdleIconRightImage = null;
            this.btnhome.IndicateFocus = true;
            this.btnhome.Name = "btnhome";
            this.btnhome.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnhome.OnDisabledState.BorderRadius = 45;
            this.btnhome.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnhome.OnDisabledState.BorderThickness = 1;
            this.btnhome.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnhome.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnhome.OnDisabledState.IconLeftImage = null;
            this.btnhome.OnDisabledState.IconRightImage = null;
            this.btnhome.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(246)))), ((int)(((byte)(246)))));
            this.btnhome.onHoverState.BorderRadius = 45;
            this.btnhome.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnhome.onHoverState.BorderThickness = 1;
            this.btnhome.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(220)))), ((int)(((byte)(220)))), ((int)(((byte)(220)))));
            this.btnhome.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnhome.onHoverState.IconLeftImage = null;
            this.btnhome.onHoverState.IconRightImage = null;
            this.btnhome.OnIdleState.BorderColor = System.Drawing.SystemColors.Control;
            this.btnhome.OnIdleState.BorderRadius = 45;
            this.btnhome.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnhome.OnIdleState.BorderThickness = 1;
            this.btnhome.OnIdleState.FillColor = System.Drawing.Color.Silver;
            this.btnhome.OnIdleState.ForeColor = System.Drawing.Color.LavenderBlush;
            this.btnhome.OnIdleState.IconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_home_24px;
            this.btnhome.OnIdleState.IconRightImage = null;
            this.btnhome.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(132)))), ((int)(((byte)(132)))), ((int)(((byte)(132)))));
            this.btnhome.OnPressedState.BorderRadius = 45;
            this.btnhome.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnhome.OnPressedState.BorderThickness = 1;
            this.btnhome.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(105)))), ((int)(((byte)(105)))));
            this.btnhome.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnhome.OnPressedState.IconLeftImage = null;
            this.btnhome.OnPressedState.IconRightImage = null;
            this.btnhome.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnhome.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnhome.TextMarginLeft = 0;
            this.btnhome.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnhome.UseDefaultRadiusAndThickness = true;
            this.btnhome.Click += new System.EventHandler(this.btnhome_Click);
            // 
            // form_dashboard
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(226)))), ((int)(((byte)(222)))));
            this.Controls.Add(this.panelControls);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "form_dashboard";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.bunifuPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuPanel panelControls;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnhome;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnexit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnuser;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btninv;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnorder;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnsup;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnitem;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btncat;
    }
}