
namespace Enchanter_Fashion.inventory.UserControls
{
    partial class uc_items
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(uc_items));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.dgvUser = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnremove = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnedit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnsave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txt_qty = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_price = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_name = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_item = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_bill = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuButton5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.button1 = new System.Windows.Forms.Button();
            this.button2 = new System.Windows.Forms.Button();
            this.button3 = new System.Windows.Forms.Button();
            this.button4 = new System.Windows.Forms.Button();
            this.button5 = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.dgvUser)).BeginInit();
            this.SuspendLayout();
            // 
            // dgvUser
            // 
            this.dgvUser.AllowCustomTheming = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.dgvUser.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.dgvUser.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvUser.BackgroundColor = System.Drawing.Color.White;
            this.dgvUser.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvUser.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvUser.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvUser.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.dgvUser.ColumnHeadersHeight = 40;
            this.dgvUser.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgvUser.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvUser.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvUser.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvUser.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvUser.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgvUser.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvUser.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgvUser.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvUser.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvUser.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgvUser.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvUser.CurrentTheme.Name = null;
            this.dgvUser.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgvUser.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvUser.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvUser.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvUser.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvUser.DefaultCellStyle = dataGridViewCellStyle6;
            this.dgvUser.EnableHeadersVisualStyles = false;
            this.dgvUser.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvUser.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgvUser.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvUser.HeaderForeColor = System.Drawing.Color.White;
            this.dgvUser.Location = new System.Drawing.Point(4, 280);
            this.dgvUser.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.dgvUser.Name = "dgvUser";
            this.dgvUser.RowHeadersVisible = false;
            this.dgvUser.RowHeadersWidth = 62;
            this.dgvUser.RowTemplate.Height = 40;
            this.dgvUser.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvUser.Size = new System.Drawing.Size(626, 278);
            this.dgvUser.TabIndex = 1;
            this.dgvUser.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // btnremove
            // 
            this.btnremove.AllowAnimations = true;
            this.btnremove.AllowMouseEffects = true;
            this.btnremove.AllowToggling = false;
            this.btnremove.AnimationSpeed = 200;
            this.btnremove.AutoGenerateColors = false;
            this.btnremove.AutoRoundBorders = false;
            this.btnremove.AutoSizeLeftIcon = true;
            this.btnremove.AutoSizeRightIcon = true;
            this.btnremove.BackColor = System.Drawing.Color.Transparent;
            this.btnremove.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.btnremove.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnremove.BackgroundImage")));
            this.btnremove.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnremove.ButtonText = "REMOVE";
            this.btnremove.ButtonTextMarginLeft = 0;
            this.btnremove.ColorContrastOnClick = 45;
            this.btnremove.ColorContrastOnHover = 45;
            this.btnremove.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnremove.CustomizableEdges = borderEdges6;
            this.btnremove.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnremove.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnremove.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnremove.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnremove.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnremove.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnremove.ForeColor = System.Drawing.Color.White;
            this.btnremove.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnremove.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnremove.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnremove.IconMarginLeft = 11;
            this.btnremove.IconPadding = 10;
            this.btnremove.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnremove.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnremove.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnremove.IconSize = 25;
            this.btnremove.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnremove.IdleBorderRadius = 1;
            this.btnremove.IdleBorderThickness = 1;
            this.btnremove.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.btnremove.IdleIconLeftImage = null;
            this.btnremove.IdleIconRightImage = null;
            this.btnremove.IndicateFocus = false;
            this.btnremove.Location = new System.Drawing.Point(831, 48);
            this.btnremove.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.btnremove.Name = "btnremove";
            this.btnremove.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnremove.OnDisabledState.BorderRadius = 1;
            this.btnremove.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnremove.OnDisabledState.BorderThickness = 1;
            this.btnremove.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnremove.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnremove.OnDisabledState.IconLeftImage = null;
            this.btnremove.OnDisabledState.IconRightImage = null;
            this.btnremove.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnremove.onHoverState.BorderRadius = 1;
            this.btnremove.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnremove.onHoverState.BorderThickness = 1;
            this.btnremove.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnremove.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnremove.onHoverState.IconLeftImage = null;
            this.btnremove.onHoverState.IconRightImage = null;
            this.btnremove.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnremove.OnIdleState.BorderRadius = 1;
            this.btnremove.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnremove.OnIdleState.BorderThickness = 1;
            this.btnremove.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.btnremove.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnremove.OnIdleState.IconLeftImage = null;
            this.btnremove.OnIdleState.IconRightImage = null;
            this.btnremove.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnremove.OnPressedState.BorderRadius = 1;
            this.btnremove.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnremove.OnPressedState.BorderThickness = 1;
            this.btnremove.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnremove.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnremove.OnPressedState.IconLeftImage = null;
            this.btnremove.OnPressedState.IconRightImage = null;
            this.btnremove.Size = new System.Drawing.Size(138, 46);
            this.btnremove.TabIndex = 2;
            this.btnremove.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnremove.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnremove.TextMarginLeft = 0;
            this.btnremove.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnremove.UseDefaultRadiusAndThickness = true;
            // 
            // btnedit
            // 
            this.btnedit.AllowAnimations = true;
            this.btnedit.AllowMouseEffects = true;
            this.btnedit.AllowToggling = false;
            this.btnedit.AnimationSpeed = 200;
            this.btnedit.AutoGenerateColors = false;
            this.btnedit.AutoRoundBorders = false;
            this.btnedit.AutoSizeLeftIcon = true;
            this.btnedit.AutoSizeRightIcon = true;
            this.btnedit.BackColor = System.Drawing.Color.Transparent;
            this.btnedit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.btnedit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnedit.BackgroundImage")));
            this.btnedit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnedit.ButtonText = "EDIT";
            this.btnedit.ButtonTextMarginLeft = 0;
            this.btnedit.ColorContrastOnClick = 45;
            this.btnedit.ColorContrastOnHover = 45;
            this.btnedit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnedit.CustomizableEdges = borderEdges7;
            this.btnedit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnedit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnedit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnedit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnedit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnedit.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnedit.ForeColor = System.Drawing.Color.White;
            this.btnedit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnedit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnedit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnedit.IconMarginLeft = 11;
            this.btnedit.IconPadding = 10;
            this.btnedit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnedit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnedit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnedit.IconSize = 25;
            this.btnedit.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnedit.IdleBorderRadius = 1;
            this.btnedit.IdleBorderThickness = 1;
            this.btnedit.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.btnedit.IdleIconLeftImage = null;
            this.btnedit.IdleIconRightImage = null;
            this.btnedit.IndicateFocus = false;
            this.btnedit.Location = new System.Drawing.Point(831, 99);
            this.btnedit.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.btnedit.Name = "btnedit";
            this.btnedit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnedit.OnDisabledState.BorderRadius = 1;
            this.btnedit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnedit.OnDisabledState.BorderThickness = 1;
            this.btnedit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnedit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnedit.OnDisabledState.IconLeftImage = null;
            this.btnedit.OnDisabledState.IconRightImage = null;
            this.btnedit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnedit.onHoverState.BorderRadius = 1;
            this.btnedit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnedit.onHoverState.BorderThickness = 1;
            this.btnedit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnedit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnedit.onHoverState.IconLeftImage = null;
            this.btnedit.onHoverState.IconRightImage = null;
            this.btnedit.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnedit.OnIdleState.BorderRadius = 1;
            this.btnedit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnedit.OnIdleState.BorderThickness = 1;
            this.btnedit.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.btnedit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnedit.OnIdleState.IconLeftImage = null;
            this.btnedit.OnIdleState.IconRightImage = null;
            this.btnedit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnedit.OnPressedState.BorderRadius = 1;
            this.btnedit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnedit.OnPressedState.BorderThickness = 1;
            this.btnedit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnedit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnedit.OnPressedState.IconLeftImage = null;
            this.btnedit.OnPressedState.IconRightImage = null;
            this.btnedit.Size = new System.Drawing.Size(138, 46);
            this.btnedit.TabIndex = 2;
            this.btnedit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnedit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnedit.TextMarginLeft = 0;
            this.btnedit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnedit.UseDefaultRadiusAndThickness = true;
            this.btnedit.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // bunifuButton4
            // 
            this.bunifuButton4.AllowAnimations = true;
            this.bunifuButton4.AllowMouseEffects = true;
            this.bunifuButton4.AllowToggling = false;
            this.bunifuButton4.AnimationSpeed = 200;
            this.bunifuButton4.AutoGenerateColors = false;
            this.bunifuButton4.AutoRoundBorders = false;
            this.bunifuButton4.AutoSizeLeftIcon = true;
            this.bunifuButton4.AutoSizeRightIcon = true;
            this.bunifuButton4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.bunifuButton4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.BackgroundImage")));
            this.bunifuButton4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.ButtonText = "";
            this.bunifuButton4.ButtonTextMarginLeft = 0;
            this.bunifuButton4.ColorContrastOnClick = 45;
            this.bunifuButton4.ColorContrastOnHover = 45;
            this.bunifuButton4.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton4.CustomizableEdges = borderEdges8;
            this.bunifuButton4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton4.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton4.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton4.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton4.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton4.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton4.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton4.IconMarginLeft = 11;
            this.bunifuButton4.IconPadding = 10;
            this.bunifuButton4.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton4.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton4.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton4.IconSize = 25;
            this.bunifuButton4.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton4.IdleBorderRadius = 1;
            this.bunifuButton4.IdleBorderThickness = 1;
            this.bunifuButton4.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.bunifuButton4.IdleIconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_search_24px;
            this.bunifuButton4.IdleIconRightImage = null;
            this.bunifuButton4.IndicateFocus = false;
            this.bunifuButton4.Location = new System.Drawing.Point(831, 211);
            this.bunifuButton4.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuButton4.Name = "bunifuButton4";
            this.bunifuButton4.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton4.OnDisabledState.BorderRadius = 1;
            this.bunifuButton4.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnDisabledState.BorderThickness = 1;
            this.bunifuButton4.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton4.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton4.OnDisabledState.IconLeftImage = null;
            this.bunifuButton4.OnDisabledState.IconRightImage = null;
            this.bunifuButton4.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton4.onHoverState.BorderRadius = 1;
            this.bunifuButton4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.onHoverState.BorderThickness = 1;
            this.bunifuButton4.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton4.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.onHoverState.IconLeftImage = null;
            this.bunifuButton4.onHoverState.IconRightImage = null;
            this.bunifuButton4.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton4.OnIdleState.BorderRadius = 1;
            this.bunifuButton4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnIdleState.BorderThickness = 1;
            this.bunifuButton4.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.bunifuButton4.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.OnIdleState.IconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_search_24px;
            this.bunifuButton4.OnIdleState.IconRightImage = null;
            this.bunifuButton4.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton4.OnPressedState.BorderRadius = 1;
            this.bunifuButton4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnPressedState.BorderThickness = 1;
            this.bunifuButton4.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton4.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.OnPressedState.IconLeftImage = null;
            this.bunifuButton4.OnPressedState.IconRightImage = null;
            this.bunifuButton4.Size = new System.Drawing.Size(45, 46);
            this.bunifuButton4.TabIndex = 2;
            this.bunifuButton4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton4.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton4.TextMarginLeft = 0;
            this.bunifuButton4.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton4.UseDefaultRadiusAndThickness = true;
            // 
            // btnsave
            // 
            this.btnsave.AllowAnimations = true;
            this.btnsave.AllowMouseEffects = true;
            this.btnsave.AllowToggling = false;
            this.btnsave.AnimationSpeed = 200;
            this.btnsave.AutoGenerateColors = false;
            this.btnsave.AutoRoundBorders = false;
            this.btnsave.AutoSizeLeftIcon = true;
            this.btnsave.AutoSizeRightIcon = true;
            this.btnsave.BackColor = System.Drawing.Color.Transparent;
            this.btnsave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.btnsave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnsave.BackgroundImage")));
            this.btnsave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.ButtonText = "SAVE";
            this.btnsave.ButtonTextMarginLeft = 0;
            this.btnsave.ColorContrastOnClick = 45;
            this.btnsave.ColorContrastOnHover = 45;
            this.btnsave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnsave.CustomizableEdges = borderEdges9;
            this.btnsave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnsave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnsave.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnsave.ForeColor = System.Drawing.Color.White;
            this.btnsave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnsave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnsave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnsave.IconMarginLeft = 11;
            this.btnsave.IconPadding = 10;
            this.btnsave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnsave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnsave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnsave.IconSize = 25;
            this.btnsave.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnsave.IdleBorderRadius = 1;
            this.btnsave.IdleBorderThickness = 1;
            this.btnsave.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.btnsave.IdleIconLeftImage = null;
            this.btnsave.IdleIconRightImage = null;
            this.btnsave.IndicateFocus = false;
            this.btnsave.Location = new System.Drawing.Point(831, 155);
            this.btnsave.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.btnsave.Name = "btnsave";
            this.btnsave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsave.OnDisabledState.BorderRadius = 1;
            this.btnsave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.OnDisabledState.BorderThickness = 1;
            this.btnsave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsave.OnDisabledState.IconLeftImage = null;
            this.btnsave.OnDisabledState.IconRightImage = null;
            this.btnsave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnsave.onHoverState.BorderRadius = 1;
            this.btnsave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.onHoverState.BorderThickness = 1;
            this.btnsave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnsave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnsave.onHoverState.IconLeftImage = null;
            this.btnsave.onHoverState.IconRightImage = null;
            this.btnsave.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnsave.OnIdleState.BorderRadius = 1;
            this.btnsave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.OnIdleState.BorderThickness = 1;
            this.btnsave.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.btnsave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnsave.OnIdleState.IconLeftImage = null;
            this.btnsave.OnIdleState.IconRightImage = null;
            this.btnsave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnsave.OnPressedState.BorderRadius = 1;
            this.btnsave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnsave.OnPressedState.BorderThickness = 1;
            this.btnsave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnsave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnsave.OnPressedState.IconLeftImage = null;
            this.btnsave.OnPressedState.IconRightImage = null;
            this.btnsave.Size = new System.Drawing.Size(138, 46);
            this.btnsave.TabIndex = 2;
            this.btnsave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnsave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnsave.TextMarginLeft = 0;
            this.btnsave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnsave.UseDefaultRadiusAndThickness = true;
            this.btnsave.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // txt_qty
            // 
            this.txt_qty.AcceptsReturn = false;
            this.txt_qty.AcceptsTab = false;
            this.txt_qty.AnimationSpeed = 200;
            this.txt_qty.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_qty.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_qty.BackColor = System.Drawing.Color.Transparent;
            this.txt_qty.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_qty.BackgroundImage")));
            this.txt_qty.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_qty.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_qty.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_qty.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_qty.BorderRadius = 1;
            this.txt_qty.BorderThickness = 1;
            this.txt_qty.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_qty.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_qty.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_qty.DefaultText = "";
            this.txt_qty.FillColor = System.Drawing.Color.White;
            this.txt_qty.HideSelection = true;
            this.txt_qty.IconLeft = null;
            this.txt_qty.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_qty.IconPadding = 10;
            this.txt_qty.IconRight = null;
            this.txt_qty.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_qty.Lines = new string[0];
            this.txt_qty.Location = new System.Drawing.Point(447, 145);
            this.txt_qty.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.txt_qty.MaxLength = 32767;
            this.txt_qty.MinimumSize = new System.Drawing.Size(2, 2);
            this.txt_qty.Modified = false;
            this.txt_qty.Multiline = false;
            this.txt_qty.Name = "txt_qty";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_qty.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_qty.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_qty.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_qty.OnIdleState = stateProperties24;
            this.txt_qty.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.txt_qty.PasswordChar = '\0';
            this.txt_qty.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_qty.PlaceholderText = "Enter text";
            this.txt_qty.ReadOnly = false;
            this.txt_qty.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_qty.SelectedText = "";
            this.txt_qty.SelectionLength = 0;
            this.txt_qty.SelectionStart = 0;
            this.txt_qty.ShortcutsEnabled = true;
            this.txt_qty.Size = new System.Drawing.Size(183, 42);
            this.txt_qty.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_qty.TabIndex = 0;
            this.txt_qty.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_qty.TextMarginBottom = 0;
            this.txt_qty.TextMarginLeft = 3;
            this.txt_qty.TextMarginTop = 0;
            this.txt_qty.TextPlaceholder = "Enter text";
            this.txt_qty.UseSystemPasswordChar = false;
            this.txt_qty.WordWrap = true;
            // 
            // txt_price
            // 
            this.txt_price.AcceptsReturn = false;
            this.txt_price.AcceptsTab = false;
            this.txt_price.AnimationSpeed = 200;
            this.txt_price.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_price.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_price.BackColor = System.Drawing.Color.Transparent;
            this.txt_price.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_price.BackgroundImage")));
            this.txt_price.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_price.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_price.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_price.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_price.BorderRadius = 1;
            this.txt_price.BorderThickness = 1;
            this.txt_price.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_price.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_price.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_price.DefaultText = "";
            this.txt_price.FillColor = System.Drawing.Color.White;
            this.txt_price.HideSelection = true;
            this.txt_price.IconLeft = null;
            this.txt_price.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_price.IconPadding = 10;
            this.txt_price.IconRight = null;
            this.txt_price.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_price.Lines = new string[0];
            this.txt_price.Location = new System.Drawing.Point(227, 145);
            this.txt_price.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.txt_price.MaxLength = 32767;
            this.txt_price.MinimumSize = new System.Drawing.Size(2, 2);
            this.txt_price.Modified = false;
            this.txt_price.Multiline = false;
            this.txt_price.Name = "txt_price";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_price.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_price.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_price.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_price.OnIdleState = stateProperties28;
            this.txt_price.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.txt_price.PasswordChar = '\0';
            this.txt_price.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_price.PlaceholderText = "Enter text";
            this.txt_price.ReadOnly = false;
            this.txt_price.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_price.SelectedText = "";
            this.txt_price.SelectionLength = 0;
            this.txt_price.SelectionStart = 0;
            this.txt_price.ShortcutsEnabled = true;
            this.txt_price.Size = new System.Drawing.Size(183, 42);
            this.txt_price.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_price.TabIndex = 0;
            this.txt_price.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_price.TextMarginBottom = 0;
            this.txt_price.TextMarginLeft = 3;
            this.txt_price.TextMarginTop = 0;
            this.txt_price.TextPlaceholder = "Enter text";
            this.txt_price.UseSystemPasswordChar = false;
            this.txt_price.WordWrap = true;
            // 
            // txt_name
            // 
            this.txt_name.AcceptsReturn = false;
            this.txt_name.AcceptsTab = false;
            this.txt_name.AnimationSpeed = 200;
            this.txt_name.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_name.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_name.BackColor = System.Drawing.Color.Transparent;
            this.txt_name.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_name.BackgroundImage")));
            this.txt_name.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_name.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_name.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_name.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_name.BorderRadius = 1;
            this.txt_name.BorderThickness = 1;
            this.txt_name.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_name.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_name.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_name.DefaultText = "";
            this.txt_name.FillColor = System.Drawing.Color.White;
            this.txt_name.HideSelection = true;
            this.txt_name.IconLeft = null;
            this.txt_name.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_name.IconPadding = 10;
            this.txt_name.IconRight = null;
            this.txt_name.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_name.Lines = new string[0];
            this.txt_name.Location = new System.Drawing.Point(4, 145);
            this.txt_name.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.txt_name.MaxLength = 32767;
            this.txt_name.MinimumSize = new System.Drawing.Size(2, 2);
            this.txt_name.Modified = false;
            this.txt_name.Multiline = false;
            this.txt_name.Name = "txt_name";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_name.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_name.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_name.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_name.OnIdleState = stateProperties32;
            this.txt_name.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.txt_name.PasswordChar = '\0';
            this.txt_name.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_name.PlaceholderText = "Enter text";
            this.txt_name.ReadOnly = false;
            this.txt_name.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_name.SelectedText = "";
            this.txt_name.SelectionLength = 0;
            this.txt_name.SelectionStart = 0;
            this.txt_name.ShortcutsEnabled = true;
            this.txt_name.Size = new System.Drawing.Size(183, 42);
            this.txt_name.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_name.TabIndex = 0;
            this.txt_name.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_name.TextMarginBottom = 0;
            this.txt_name.TextMarginLeft = 3;
            this.txt_name.TextMarginTop = 0;
            this.txt_name.TextPlaceholder = "Enter text";
            this.txt_name.UseSystemPasswordChar = false;
            this.txt_name.WordWrap = true;
            // 
            // txt_item
            // 
            this.txt_item.AcceptsReturn = false;
            this.txt_item.AcceptsTab = false;
            this.txt_item.AnimationSpeed = 200;
            this.txt_item.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_item.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_item.BackColor = System.Drawing.Color.Transparent;
            this.txt_item.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_item.BackgroundImage")));
            this.txt_item.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_item.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_item.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_item.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_item.BorderRadius = 1;
            this.txt_item.BorderThickness = 1;
            this.txt_item.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_item.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_item.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_item.DefaultText = "";
            this.txt_item.FillColor = System.Drawing.Color.White;
            this.txt_item.HideSelection = true;
            this.txt_item.IconLeft = null;
            this.txt_item.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_item.IconPadding = 10;
            this.txt_item.IconRight = null;
            this.txt_item.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_item.Lines = new string[0];
            this.txt_item.Location = new System.Drawing.Point(369, 51);
            this.txt_item.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.txt_item.MaxLength = 32767;
            this.txt_item.MinimumSize = new System.Drawing.Size(2, 2);
            this.txt_item.Modified = false;
            this.txt_item.Multiline = false;
            this.txt_item.Name = "txt_item";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_item.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_item.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_item.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_item.OnIdleState = stateProperties36;
            this.txt_item.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.txt_item.PasswordChar = '\0';
            this.txt_item.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_item.PlaceholderText = "Enter text";
            this.txt_item.ReadOnly = false;
            this.txt_item.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_item.SelectedText = "";
            this.txt_item.SelectionLength = 0;
            this.txt_item.SelectionStart = 0;
            this.txt_item.ShortcutsEnabled = true;
            this.txt_item.Size = new System.Drawing.Size(183, 42);
            this.txt_item.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_item.TabIndex = 0;
            this.txt_item.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_item.TextMarginBottom = 0;
            this.txt_item.TextMarginLeft = 3;
            this.txt_item.TextMarginTop = 0;
            this.txt_item.TextPlaceholder = "Enter text";
            this.txt_item.UseSystemPasswordChar = false;
            this.txt_item.WordWrap = true;
            // 
            // txt_bill
            // 
            this.txt_bill.AcceptsReturn = false;
            this.txt_bill.AcceptsTab = false;
            this.txt_bill.AnimationSpeed = 200;
            this.txt_bill.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_bill.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_bill.BackColor = System.Drawing.Color.Transparent;
            this.txt_bill.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_bill.BackgroundImage")));
            this.txt_bill.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_bill.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_bill.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_bill.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_bill.BorderRadius = 1;
            this.txt_bill.BorderThickness = 1;
            this.txt_bill.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_bill.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_bill.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txt_bill.DefaultText = "";
            this.txt_bill.FillColor = System.Drawing.Color.White;
            this.txt_bill.HideSelection = true;
            this.txt_bill.IconLeft = null;
            this.txt_bill.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_bill.IconPadding = 10;
            this.txt_bill.IconRight = null;
            this.txt_bill.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_bill.Lines = new string[0];
            this.txt_bill.Location = new System.Drawing.Point(58, 51);
            this.txt_bill.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.txt_bill.MaxLength = 32767;
            this.txt_bill.MinimumSize = new System.Drawing.Size(2, 2);
            this.txt_bill.Modified = false;
            this.txt_bill.Multiline = false;
            this.txt_bill.Name = "txt_bill";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_bill.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_bill.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_bill.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_bill.OnIdleState = stateProperties40;
            this.txt_bill.Padding = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.txt_bill.PasswordChar = '\0';
            this.txt_bill.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_bill.PlaceholderText = "Enter text";
            this.txt_bill.ReadOnly = false;
            this.txt_bill.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_bill.SelectedText = "";
            this.txt_bill.SelectionLength = 0;
            this.txt_bill.SelectionStart = 0;
            this.txt_bill.ShortcutsEnabled = true;
            this.txt_bill.Size = new System.Drawing.Size(183, 42);
            this.txt_bill.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_bill.TabIndex = 0;
            this.txt_bill.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_bill.TextMarginBottom = 0;
            this.txt_bill.TextMarginLeft = 3;
            this.txt_bill.TextMarginTop = 0;
            this.txt_bill.TextPlaceholder = "Enter text";
            this.txt_bill.UseSystemPasswordChar = false;
            this.txt_bill.WordWrap = true;
            // 
            // bunifuButton5
            // 
            this.bunifuButton5.AllowAnimations = true;
            this.bunifuButton5.AllowMouseEffects = true;
            this.bunifuButton5.AllowToggling = false;
            this.bunifuButton5.AnimationSpeed = 200;
            this.bunifuButton5.AutoGenerateColors = false;
            this.bunifuButton5.AutoRoundBorders = false;
            this.bunifuButton5.AutoSizeLeftIcon = true;
            this.bunifuButton5.AutoSizeRightIcon = true;
            this.bunifuButton5.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton5.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.bunifuButton5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton5.BackgroundImage")));
            this.bunifuButton5.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.ButtonText = "";
            this.bunifuButton5.ButtonTextMarginLeft = 0;
            this.bunifuButton5.ColorContrastOnClick = 45;
            this.bunifuButton5.ColorContrastOnHover = 45;
            this.bunifuButton5.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.bunifuButton5.CustomizableEdges = borderEdges10;
            this.bunifuButton5.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton5.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton5.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton5.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton5.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton5.ForeColor = System.Drawing.Color.White;
            this.bunifuButton5.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton5.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton5.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton5.IconMarginLeft = 11;
            this.bunifuButton5.IconPadding = 10;
            this.bunifuButton5.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton5.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton5.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton5.IconSize = 25;
            this.bunifuButton5.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton5.IdleBorderRadius = 1;
            this.bunifuButton5.IdleBorderThickness = 1;
            this.bunifuButton5.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.bunifuButton5.IdleIconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_search_24px;
            this.bunifuButton5.IdleIconRightImage = null;
            this.bunifuButton5.IndicateFocus = false;
            this.bunifuButton5.Location = new System.Drawing.Point(884, 211);
            this.bunifuButton5.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuButton5.Name = "bunifuButton5";
            this.bunifuButton5.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton5.OnDisabledState.BorderRadius = 1;
            this.bunifuButton5.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.OnDisabledState.BorderThickness = 1;
            this.bunifuButton5.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton5.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton5.OnDisabledState.IconLeftImage = null;
            this.bunifuButton5.OnDisabledState.IconRightImage = null;
            this.bunifuButton5.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton5.onHoverState.BorderRadius = 1;
            this.bunifuButton5.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.onHoverState.BorderThickness = 1;
            this.bunifuButton5.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton5.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton5.onHoverState.IconLeftImage = null;
            this.bunifuButton5.onHoverState.IconRightImage = null;
            this.bunifuButton5.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton5.OnIdleState.BorderRadius = 1;
            this.bunifuButton5.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.OnIdleState.BorderThickness = 1;
            this.bunifuButton5.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.bunifuButton5.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton5.OnIdleState.IconLeftImage = global::Enchanter_Fashion.Properties.Resources.icons8_search_24px;
            this.bunifuButton5.OnIdleState.IconRightImage = null;
            this.bunifuButton5.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton5.OnPressedState.BorderRadius = 1;
            this.bunifuButton5.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton5.OnPressedState.BorderThickness = 1;
            this.bunifuButton5.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton5.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton5.OnPressedState.IconLeftImage = null;
            this.bunifuButton5.OnPressedState.IconRightImage = null;
            this.bunifuButton5.Size = new System.Drawing.Size(45, 46);
            this.bunifuButton5.TabIndex = 2;
            this.bunifuButton5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton5.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton5.TextMarginLeft = 0;
            this.bunifuButton5.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton5.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(64, 26);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(51, 25);
            this.bunifuLabel1.TabIndex = 3;
            this.bunifuLabel1.Text = "Bill No";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.Location = new System.Drawing.Point(375, 26);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(59, 25);
            this.bunifuLabel2.TabIndex = 3;
            this.bunifuLabel2.Text = "Item ID";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel3.Location = new System.Drawing.Point(10, 120);
            this.bunifuLabel3.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(88, 25);
            this.bunifuLabel3.TabIndex = 3;
            this.bunifuLabel3.Text = "Item Name";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel4.Location = new System.Drawing.Point(232, 120);
            this.bunifuLabel4.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(74, 25);
            this.bunifuLabel4.TabIndex = 3;
            this.bunifuLabel4.Text = "Unit Price";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel5.Location = new System.Drawing.Point(453, 120);
            this.bunifuLabel5.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(68, 25);
            this.bunifuLabel5.TabIndex = 3;
            this.bunifuLabel5.Text = "Quantity";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.button1.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button1.ForeColor = System.Drawing.Color.White;
            this.button1.Location = new System.Drawing.Point(30, 211);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(138, 46);
            this.button1.TabIndex = 4;
            this.button1.Text = "SAVE";
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.button2.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button2.ForeColor = System.Drawing.Color.White;
            this.button2.Location = new System.Drawing.Point(241, 211);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(138, 46);
            this.button2.TabIndex = 4;
            this.button2.Text = "EDIT";
            this.button2.UseVisualStyleBackColor = false;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.button3.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button3.ForeColor = System.Drawing.Color.White;
            this.button3.Location = new System.Drawing.Point(447, 211);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(138, 46);
            this.button3.TabIndex = 4;
            this.button3.Text = "REMOVE";
            this.button3.UseVisualStyleBackColor = false;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // button4
            // 
            this.button4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.button4.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button4.Image = global::Enchanter_Fashion.Properties.Resources.icons8_search_24px1;
            this.button4.Location = new System.Drawing.Point(253, 48);
            this.button4.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(53, 48);
            this.button4.TabIndex = 75;
            this.button4.UseVisualStyleBackColor = false;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            // 
            // button5
            // 
            this.button5.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.button5.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.button5.Image = global::Enchanter_Fashion.Properties.Resources.icons8_search_24px1;
            this.button5.Location = new System.Drawing.Point(564, 48);
            this.button5.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(53, 48);
            this.button5.TabIndex = 76;
            this.button5.UseVisualStyleBackColor = false;
            this.button5.Click += new System.EventHandler(this.button5_Click);
            // 
            // uc_items
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.button5);
            this.Controls.Add(this.button4);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.btnremove);
            this.Controls.Add(this.btnedit);
            this.Controls.Add(this.bunifuButton5);
            this.Controls.Add(this.bunifuButton4);
            this.Controls.Add(this.btnsave);
            this.Controls.Add(this.dgvUser);
            this.Controls.Add(this.txt_qty);
            this.Controls.Add(this.txt_price);
            this.Controls.Add(this.txt_name);
            this.Controls.Add(this.txt_item);
            this.Controls.Add(this.txt_bill);
            this.Name = "uc_items";
            this.Size = new System.Drawing.Size(1138, 945);
            ((System.ComponentModel.ISupportInitialize)(this.dgvUser)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox txt_bill;
        private Bunifu.UI.WinForms.BunifuTextBox txt_item;
        private Bunifu.UI.WinForms.BunifuTextBox txt_name;
        private Bunifu.UI.WinForms.BunifuTextBox txt_price;
        private Bunifu.UI.WinForms.BunifuTextBox txt_qty;
        private Bunifu.UI.WinForms.BunifuDataGridView dgvUser;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnsave;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnedit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnremove;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Button button3;
        private System.Windows.Forms.Button button4;
        private System.Windows.Forms.Button button5;
    }
}
